# Serve .mov audio files in local dev
webrick:
  mime_types:
    .mov: video/quicktime

# Site
locale: "en-UK"
title: "Jingzhi / Homepage"
name: "Jingzhi Gong"
description: "personal description"
url: https://gjz78910.github.io
baseurl: ""
repository: "gjz78910/gjz78910.github.io"
timezone: America/Los_Angeles

# Author
author:
  name: "Jingzhi Gong"
  avatar: "profile.png"
  bio: "Research Associate for King's College London, PhD from Loughborough University"
  location: "London, UK"
  googlescholar: "https://scholar.google.com/citations?user=m63bkGEAAAAJ"
  email: jingzhi.gong@kcl.ac.uk
  github: "gjz78910"
  instagram: "gongjingzhi"
  linkedin: "jingzhi-gong-546858b5"
  twitter: "GONGJINGZHI"

# Build input
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - vendor

# Markdown
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: printer
      author_profile: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# HTML compression (used by _layouts/compress.html)
compress_html:
  clippings: all
  ignore:
    envs: development
